### ISSUE TITLE
M353 not working in competitive and tactical layout

### ISSUE THREAD

**Issue by NOOTLORD** [Azarael/BallisticPro#33]
Primary and secondary fire refuse to work. It seems something does not get assigned correctly since the weapon modes also don't show up.
I spotted something odd when i have showdebug on, i noticed it says primaryfire2 but on all other working guns it says primaryfire1. No clue why that is but maybe it will point in the right direction for a fix

**Comment by MarcMoylan** [comment]
InitialWeaponMode=3 missing, fixed and pushed
