### ISSUE TITLE
M575 Machinegun

### ISSUE THREAD

**Issue by Azarael** [Azarael/BallisticPro#42]
FPV: Tracers appear from player centre mass rather than weapon tip
TPV: Muzzle flash not bound to tip

**Comment by MarcMoylan** [comment]
tracers and flashes appear fixed
amp add animation needs adjusting, gun needs to be pulled in when amp is added

**Comment by MarcMoylan** [comment]
polished

**Comment by Azarael** [comment]
Resolved?

**Comment by MarcMoylan** [comment]
Ideally wanted to get the turret fixed and amp add anim improved, but that can be 2.8, I'll close this.
