### ISSUE TITLE
Ballisticscope fire not working correctly

### ISSUE THREAD

**Issue by NOOTLORD** [Azarael/BallisticPro#58]
**Bug description:**
When a weapon has Ballisticscopefire as its alternate fire mode u will be able to scope and fire ONE bullet and then it stops. Whilst this class is more used to handle the ADS how would we go about fixing this? Apply the primaryfire class to the alternate fire?
Also when u fire and press the alternate fire at the same time the weapon will scope in like it is in toggle mode

**Branch:**
Dev

**Build from commit:**
https://github.com/Azarael/BallisticPro/commit/92087344c82005b80b362fcb5108b1eecd9213b3

**How to replicate:**
Grab the **AH250 Assault Pistol** and press the alternate fire button and try to fire more then one bullet :) Once u tried hard enough now press the fire and alternate fire mode button at the same time and u will see the gun scope in like its in toggle mode

**Comment by MarcMoylan** [comment]
fixed the issue where single fire weapons wouldnt reset their firecounter while scope was being held
