### ISSUE TITLE
Headshots not being awarded

### ISSUE THREAD

**Issue by NOOTLORD** [Azarael/BallisticPro#68]
**Bug description:**
When u get a headshot u expect to get the Headshot reward but nothing appears.
The game registers it as a headshot since the killfeed says headshot and the head is gone on the poor soul who u just dinked in the face.

**Branch:**
Dev

**Build from commit:**
e2ca97a

**Online or Offline?**
Both

**How to replicate:**
Get a headshot with a XK2 or any gun (at least it seems a lot of weapons have this issue)

**Comment by Azarael** [comment]
Intentional.

Only power weapons report headshots using the announcer, otherwise you get constant spam of "Head shot" from auto weapons in Tactical.
